sonar.projectKey=Tomas-Mart_llm-rag-spring
sonar.organization=tomas-mart
sonar.host.url=https://sonarcloud.io
# ?????
sonar.language=java
sonar.java.source=21
# ???? ? ??????????
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.test.inclusions=**/*Test.java,**/*IT.java
# ????????
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.java.coveragePlugin=jacoco
# ??????????
sonar.exclusions=**/generated/**/*.java,**/model/**/*.java
sonar.coverage.exclusions=**/config/**/*.java,**/exception/**/*.java